package tech.azurestar.kmp.ecommercecustomer

const val SUPABASE_URL = "https://ypwrnnvolijqbvzbkbxk.supabase.co"
const val SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwd3JubnZvbGlqcWJ2emJrYnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAyMDY5MzMsImV4cCI6MjA0NTc4MjkzM30.gBjGVlG_iXjOdUS0vW68povlXBMyxpfCQosNf4c8F58"
const val SUPABASE_DB_PASSWORD = "uTuvKzidQU0QO0uc"
const val RESEND_KEY = "re_BjkANYtU_4EAQLjwauS19n2u2sNYLBaPM"